[package]
name = "llvm-cov-json"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.75"
camino = {version="1.1.6", features = ["serde"]}
serde = {version="1.0.192", features = ["derive"]}
serde_json = "1.0.108"
